use std::path::{Path, PathBuf};
use std::process::Stdio;
use tokio::process::Command;
use tokio::io::AsyncBufReadExt;
use grammers_client::Client;
use grammers_session::defs::PeerRef;
use grammers_client::types::InputMessage;
use std::fs::File;
use std::io::Write;
use serde::Deserialize;
use serde_json;

use crate::config::Config;
use crate::logger;

fn parse_yt_dlp_progress(line: &str) -> Option<(f64, String, String)> {
    if !line.contains("[download]") {
        return None;
    }
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() >= 2 {
        for i in 1..parts.len() {
            if parts[i].ends_with('%') {
                if let Ok(percent) = parts[i].trim_end_matches('%').parse::<f64>() {
                    let mut speed = "N/A".to_string();
                    let mut eta = "N/A".to_string();
                    for j in i+1..parts.len() {
                        if parts[j] == "at" && j + 1 < parts.len() {
                            speed = parts[j+1].to_string();
                        }
                        if parts[j] == "ETA" && j + 1 < parts.len() {
                            eta = parts[j+1].to_string();
                        }
                    }
                    return Some((percent, speed, eta));
                }
            }
        }
    }
    None
}

pub fn is_video_url(text: &str) -> bool {
    let text_lower = text.to_lowercase();
    text_lower.contains("youtube.com/")
        || text_lower.contains("youtu.be/")
        || text_lower.contains("twitter.com/")
        || text_lower.contains("x.com/")
        || text_lower.contains("twitch.tv/")
        || text_lower.contains("bilibili.com/")
        || text_lower.contains("bili.live/")
        || text_lower.contains("b23.tv/")
        || text_lower.contains("bilibili.tv/")
}

fn detect_platform(url: &str) -> Option<&'static str> {
    let lower = url.to_lowercase();
    if lower.contains("youtube.com") || lower.contains("youtu.be") {
        Some("youtube")
    } else if lower.contains("bilibili.com")
        || lower.contains("bili.live")
        || lower.contains("b23.tv")
        || lower.contains("bilibili.tv")
    {
        Some("bilibili")
    } else if lower.contains("twitter.com") || lower.contains("x.com") {
        Some("twitter")
    } else {
        None
    }
}

fn get_domain_for_platform(platform: &str) -> String {
    match platform {
        "youtube" => ".youtube.com".to_string(),
        "bilibili" => ".bilibili.com".to_string(),
        "twitter" => ".twitter.com".to_string(),
        other => format!(".{}.com", other),
    }
}

#[derive(Deserialize, Debug)]
struct JsonCookie {
    domain: String,
    name: String,
    value: String,
    path: Option<String>,
    #[serde(rename = "expirationDate")]
    expiration_date: Option<serde_json::Value>,
    secure: Option<bool>,
}

fn convert_to_netscape_if_needed(platform: &str, content: &str) -> String {
    let trimmed = content.trim();

    // Check if JSON format
    if trimmed.starts_with('[') && trimmed.ends_with(']') {
        if let Ok(cookies) = serde_json::from_str::<Vec<JsonCookie>>(trimmed) {
            let mut netscape = String::new();
            netscape.push_str("# Netscape HTTP Cookie File\n");
            netscape.push_str("# This file was generated by magebot from JSON\n\n");
            
            let domains_to_duplicate = vec![".twitter.com".to_string(), ".x.com".to_string()];

            for c in cookies {
                let secure_str = if c.secure.unwrap_or(true) { "TRUE" } else { "FALSE" };
                let path_str = c.path.as_deref().unwrap_or("/");
                let expiry = match c.expiration_date {
                    Some(serde_json::Value::Number(num)) => num.as_f64().map(|f| f as u64).unwrap_or(2000000000),
                    _ => 2000000000,
                };
                
                if platform == "twitter" && (c.domain.contains("twitter.com") || c.domain.contains("x.com")) {
                    for dup_domain in &domains_to_duplicate {
                        netscape.push_str(&format!("{}\tTRUE\t{}\tTRUE\t{}\t{}\t{}\n", dup_domain, path_str, expiry, c.name, c.value));
                    }
                } else {
                    let subdomain_str = if c.domain.starts_with('.') { "TRUE" } else { "FALSE" };
                    netscape.push_str(&format!("{}\t{}\t{}\t{}\t{}\t{}\t{}\n", c.domain, subdomain_str, path_str, secure_str, expiry, c.name, c.value));
                }
            }
            return netscape;
        }
    }

    let is_netscape = trimmed.starts_with("# Netscape HTTP Cookie File") || trimmed.starts_with("# HTTP Cookie File");

    if is_netscape {
        if platform == "twitter" {
            let mut lines = Vec::new();
            for line in trimmed.lines() {
                lines.push(line.to_string());
                let parts: Vec<&str> = line.split('\t').collect();
                if parts.len() >= 6 {
                    let domain = parts[0];
                    if domain == ".twitter.com" {
                        let mut new_parts = parts.clone();
                        new_parts[0] = ".x.com";
                        lines.push(new_parts.join("\t"));
                    } else if domain == ".x.com" {
                        let mut new_parts = parts.clone();
                        new_parts[0] = ".twitter.com";
                        lines.push(new_parts.join("\t"));
                    }
                }
            }
            return lines.join("\n");
        }
        return trimmed.to_string();
    }
    
    let domains = match platform {
        "twitter" => vec![".twitter.com".to_string(), ".x.com".to_string()],
        other => vec![get_domain_for_platform(other)],
    };
    
    let mut netscape = String::new();
    netscape.push_str("# Netscape HTTP Cookie File\n");
    netscape.push_str("# This file was generated by magebot\n\n");
    
    for part in trimmed.split(';') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        if let Some((name, val)) = part.split_once('=') {
            let name = name.trim();
            let val = val.trim();
            if !name.is_empty() {
                for domain in &domains {
                    netscape.push_str(&format!("{}\tTRUE\t/\tTRUE\t2000000000\t{}\t{}\n", domain, name, val));
                }
            }
        }
    }
    netscape
}

pub(crate) struct TempCookieFile {
    pub(crate) path: PathBuf,
}

impl TempCookieFile {
    pub(crate) fn create(platform: &str, content: &str) -> Result<Self, String> {
        let mut path = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
        path.push(".magebot");
        let _ = std::fs::create_dir_all(&path);
        
        let random_suffix: u32 = rand::random();
        path.push(format!("temp_cookie_{}_{}.txt", platform, random_suffix));
        
        let converted_content = convert_to_netscape_if_needed(platform, content);
        
        let mut file = File::create(&path).map_err(|e| format!("Failed to create temp cookie file: {}", e))?;
        file.write_all(converted_content.as_bytes()).map_err(|e| format!("Failed to write temp cookie file: {}", e))?;
        
        Ok(Self { path })
    }
}

impl Drop for TempCookieFile {
    fn drop(&mut self) {
        if self.path.exists() {
            let _ = std::fs::remove_file(&self.path);
        }
    }
}

fn add_filtered_args(cmd: &mut Command, args_str: &str, filter_cookies: bool) {
    if filter_cookies {
        let mut words = args_str.split_whitespace().peekable();
        while let Some(&word) = words.peek() {
            if word == "--cookies-from-browser" {
                let _ = words.next(); // consume "--cookies-from-browser"
                let _ = words.next(); // consume the browser name (if any)
            } else if word.starts_with("--cookies-from-browser=") {
                let _ = words.next(); // consume "--cookies-from-browser=browser"
            } else {
                cmd.arg(words.next().unwrap());
            }
        }
    } else {
        for arg in args_str.split_whitespace() {
            cmd.arg(arg);
        }
    }
}

async fn get_expected_filename(
    yt_dlp_path: &str,
    yt_dlp_args: Option<&str>,
    temp_cookie_path: Option<&Path>,
    no_cookies: bool,
    download_dir: &Path,
    url: &str,
) -> Result<PathBuf, String> {
    let output_template = download_dir.join("%(id)s.%(ext)s");
    let output_str = output_template.to_string_lossy();

    let mut cmd = Command::new(yt_dlp_path);
    cmd.arg("--no-playlist");
    cmd.arg("--js-runtimes");
    cmd.arg("node");
    if let Some(args_str) = yt_dlp_args {
        add_filtered_args(&mut cmd, args_str, temp_cookie_path.is_some() || no_cookies);
    }
    if let Some(cookies) = temp_cookie_path {
        cmd.arg("--cookies");
        cmd.arg(cookies);
    } else if no_cookies {
        // Disable cookie handling to avoid DPAPI errors
        cmd.arg("--no-cookies");
    }
    cmd.args([
        "-o",
        &output_str,
        "--print",
        "filename",
        url,
    ]);

    let output = cmd
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .await
        .map_err(|e| format!("Failed to execute yt-dlp to query filename: {}", e))?;

    if !output.status.success() {
        let err_msg = String::from_utf8_lossy(&output.stderr);
        return Err(format!("yt-dlp filename query failed: {}", err_msg.trim()));
    }

    let filename_str = String::from_utf8_lossy(&output.stdout);
    let path_str = filename_str.trim();
    if path_str.is_empty() {
        return Err("yt-dlp returned empty filename".to_string());
    }

    Ok(PathBuf::from(path_str))
}

pub async fn handle_video_download(client: Client, config: Config, target_chat: PeerRef, url: String, msg_id: i32) {
    let yt_dlp_path = config.get_yt_dlp_path();
    let download_dir = config.get_download_dir();

    if let Err(e) = tokio::fs::create_dir_all(&download_dir).await {
        logger::error(&format!("Downloader: Failed to create download_dir: {}", e));
        let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
            revoke: true,
            id: vec![msg_id],
        };
        let _ = client.invoke(&delete_req).await;
        let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 无法创建下载目录: {}", url, e)).await;
        return;
    }

    let mut info_msg_ids = Vec::new();
    logger::info(&format!("Downloader: Starting download for URL: {}", url));
    if let Ok(msg) = client.send_message(target_chat.clone(), "📥 识别到视频链接，正在后台下载中，请稍候...").await {
        info_msg_ids.push(msg.id());
    }

    // Intercept Twitter images & videos
    let is_twitter = url.to_lowercase().contains("twitter.com") || url.to_lowercase().contains("x.com");
    if is_twitter {
        match try_download_twitter_media(&client, &target_chat, &url, msg_id, &download_dir, &mut info_msg_ids).await {
            Ok(true) => {
                return;
            }
            Ok(false) => {}
            Err(e) => {
                logger::warn(&format!("Downloader: Twitter media download check failed, falling back to yt-dlp: {}", e));
            }
        }
    }

    // Detect platform and handle cookies
    let platform = detect_platform(&url);
    let mut temp_cookie = None;
    let mut use_no_cookies = false;
    if let Some(plat) = platform {
        // Attempt to load stored encrypted cookie for the platform
        if let Ok(key) = crate::crypto::get_encryption_key() {
            if let Ok(cookies_map) = crate::crypto::load_cookies_toml() {
                if let Some(encrypted_cookie) = cookies_map.get(plat) {
                    // Decrypt and write to a temporary file
                    if let Ok(decrypted) = crate::crypto::decrypt_cookie(encrypted_cookie, &key) {
                        match TempCookieFile::create(plat, &decrypted) {
                            Ok(t) => {
                                logger::info(&format!("Downloader: Using encrypted cookie for platform '{}'", plat));
                                temp_cookie = Some(t);
                            }
                            Err(e) => {
                                logger::warn(&format!("Downloader: Failed to create temp cookie file: {}", e));
                            }
                        }
                    }
                } else {
                    // No cookie stored for this platform – tell yt-dlp not to use any cookies
                    use_no_cookies = true;
                }
            }
        }
    }

    let temp_cookie_path = temp_cookie.as_ref().map(|tc| tc.path.as_path());

    // If we decided to use --no-cookies, pass a flag via a temporary empty file path placeholder
    let no_cookies_flag = use_no_cookies;

    // Get expected output path (includes cookie handling)
    let expected_path = match get_expected_filename(&yt_dlp_path, config.yt_dlp_args.as_deref(), temp_cookie_path, no_cookies_flag, &download_dir, &url).await {
        Ok(path) => path,
        Err(e) => {
            logger::error(&format!("Downloader: Failed to get expected filename: {}", e));
            download_dir.join("video.mp4")
        }
    };

    let output_template = download_dir.join("%(id)s.%(ext)s");
    let output_str = output_template.to_string_lossy();

    logger::info(&format!("Downloader: Running yt-dlp to download to: {}", expected_path.display()));

    let mut cmd = Command::new(&yt_dlp_path);
    cmd.arg("--no-playlist");
    cmd.arg("--js-runtimes");
    cmd.arg("node");
    if let Some(ref args_str) = config.yt_dlp_args {
        add_filtered_args(&mut cmd, args_str, temp_cookie_path.is_some() || no_cookies_flag);
    }
    if let Some(cookies) = temp_cookie_path {
        cmd.arg("--cookies");
        cmd.arg(cookies);
    } else if no_cookies_flag {
        // Explicitly disable cookie usage to avoid DPAPI attempts
        cmd.arg("--no-cookies");
    }
    cmd.args([
        "-o",
        &output_str,
        &url,
    ]);

    let task_id = format!("dl_{}", url);
    let filename_display = expected_path.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "video.mp4".to_string());

    // Register active download task in IPC
    crate::ipc::update_task(
        &task_id,
        crate::ipc::TaskType::Download,
        &filename_display,
        crate::ipc::TaskStatus::Downloading {
            progress: 0.0,
            speed: "0 B/s".to_string(),
            eta: "--:--".to_string(),
        },
    );

    let mut child = match cmd
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            let err_msg = format!("Failed to spawn yt-dlp: {}", e);
            logger::error(&err_msg);
            
            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Failed(err_msg.clone()),
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut delete_ids = vec![msg_id];
            delete_ids.extend(info_msg_ids);
            if !delete_ids.is_empty() {
                let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                    revoke: true,
                    id: delete_ids,
                };
                let _ = client.invoke(&delete_req).await;
            }
            let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 运行 yt-dlp 失败: {}", url, e)).await;
            return;
        }
    };

    let stdout = child.stdout.take().unwrap();
    let stderr = child.stderr.take().unwrap();

    // Spawn task to read stdout and parse progress
    let task_id_clone = task_id.clone();
    let filename_display_clone = filename_display.clone();
    tokio::spawn(async move {
        let mut reader = tokio::io::BufReader::new(stdout).lines();
        while let Ok(Some(line)) = reader.next_line().await {
            if let Some((percent, speed, eta)) = parse_yt_dlp_progress(&line) {
                crate::ipc::update_task(
                    &task_id_clone,
                    crate::ipc::TaskType::Download,
                    &filename_display_clone,
                    crate::ipc::TaskStatus::Downloading {
                        progress: percent,
                        speed,
                        eta,
                    },
                );
            }
        }
    });

    // Capture stderr
    let mut stderr_content = String::new();
    let mut stderr_reader = tokio::io::BufReader::new(stderr).lines();
    
    let wait_result = async {
        while let Ok(Some(line)) = stderr_reader.next_line().await {
            stderr_content.push_str(&line);
            stderr_content.push('\n');
        }
        child.wait().await
    }.await;

    match wait_result {
        Ok(status) if status.success() => {
            // Update download task to Completed
            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Completed,
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut final_path = expected_path.clone();
            if !final_path.exists() {
                logger::warn(&format!(
                    "Downloader: Expected file {:?} does not exist. Scanning download directory...",
                    expected_path
                ));
                if let Ok(mut entries) = tokio::fs::read_dir(&download_dir).await {
                    let mut found = false;
                    while let Ok(Some(entry)) = entries.next_entry().await {
                        let path = entry.path();
                        if path.is_file() {
                            if let Some(stem) = expected_path.file_stem().and_then(|s| s.to_str()) {
                                if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
                                    if filename.contains(stem) {
                                        final_path = path;
                                        found = true;
                                        break;
                                    }
                                }
                             }
                        }
                    }
                    if !found {
                        logger::error("Downloader: Downloaded file not found in directory.");
                        let mut delete_ids = vec![msg_id];
                        delete_ids.extend(info_msg_ids);
                        let _ = client.invoke(&grammers_tl_types::functions::messages::DeleteMessages { revoke: true, id: delete_ids }).await;
                        let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 视频下载成功，但未能在本地找到该文件。", url)).await;
                        return;
                    }
                } else {
                    logger::error("Downloader: Downloaded file not found and directory scan failed.");
                    let mut delete_ids = vec![msg_id];
                    delete_ids.extend(info_msg_ids);
                    let _ = client.invoke(&grammers_tl_types::functions::messages::DeleteMessages { revoke: true, id: delete_ids }).await;
                    let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 视频下载成功，但未能读取下载目录。", url)).await;
                    return;
                }
            }

            logger::info(&format!("Downloader: Video downloaded successfully to {:?}", final_path));
            if let Ok(msg) = client.send_message(target_chat.clone(), "📤 下载完成，正在直接上传视频...").await {
                info_msg_ids.push(msg.id());
            }

            let upload_task_id = format!("ul_{}", final_path.file_name().unwrap().to_string_lossy());
            let upload_filename = final_path.file_name().unwrap().to_string_lossy().to_string();
            let file_size = tokio::fs::metadata(&final_path).await.map(|m| m.len()).unwrap_or(0);

            // Write metadata file for crash recovery and retry
            let ext_str = final_path.extension().and_then(|e| e.to_str()).unwrap_or("mp4");
            let meta_path = final_path.with_extension(format!("{}.meta", ext_str));
            let target_str = target_chat.id.bot_api_dialog_id().to_string();
            let meta_json = serde_json::json!({
                "url": url,
                "target": target_str
            });
            if let Ok(meta_str) = serde_json::to_string(&meta_json) {
                let _ = tokio::fs::write(&meta_path, meta_str).await;
            }

            // Register active upload task in IPC as Pending
            crate::ipc::update_task(
                &upload_task_id,
                crate::ipc::TaskType::Upload,
                &upload_filename,
                crate::ipc::TaskStatus::Pending,
            );

            // Wait for a slot in the upload queue
            let semaphore = crate::watcher::get_upload_semaphore();
            let _permit = semaphore.acquire().await;

            // Update task status to Uploading
            crate::ipc::update_task(
                &upload_task_id,
                crate::ipc::TaskType::Upload,
                &upload_filename,
                crate::ipc::TaskStatus::Uploading {
                    progress: 0.0,
                    speed: "2.4 MiB/s".to_string(),
                    eta: "--s".to_string(),
                },
            );

            // Spawn background simulation task
            let upload_task_id_clone = upload_task_id.clone();
            let upload_filename_clone = upload_filename.clone();
            let (cancel_tx, mut cancel_rx) = tokio::sync::oneshot::channel::<()>();
            
            tokio::spawn(async move {
                let speed_bytes = 2_500_000_u64; // ~2.4 MiB/s
                let mut elapsed = 0.0;
                let tick_sec = 0.5;
                loop {
                    tokio::select! {
                        _ = tokio::time::sleep(std::time::Duration::from_millis(500)) => {
                            elapsed += tick_sec;
                            let uploaded = (elapsed * speed_bytes as f64) as u64;
                            let progress = if file_size > 0 {
                                ((uploaded as f64 / file_size as f64) * 100.0).min(95.0)
                            } else {
                                95.0
                            };
                            let speed_str = "2.4 MiB/s".to_string();
                            let eta_str = if file_size > uploaded {
                                format!("{}s", ((file_size - uploaded) / speed_bytes).max(1))
                            } else {
                                "1s".to_string()
                            };

                            crate::ipc::update_task(
                                &upload_task_id_clone,
                                crate::ipc::TaskType::Upload,
                                &upload_filename_clone,
                                crate::ipc::TaskStatus::Uploading {
                                    progress,
                                    speed: speed_str,
                                    eta: eta_str,
                                },
                            );
                        }
                        _ = &mut cancel_rx => {
                            break;
                        }
                    }
                }
            });

            let caption = format!("[Uploaded] {}", url);
            let client_up = client.clone();
            let final_path_up = final_path.clone();
            let target_chat_up = target_chat.clone();
            
            let mut upload_result = Err(std::io::Error::new(std::io::ErrorKind::Other, "Upload not started"));
            // Retry up to 3 times
            for attempt in 1..=3 {
                logger::info(&format!("Downloader: Uploading video file (attempt {}): {:?}", attempt, final_path_up));
                let client_up_inner = client_up.clone();
                let final_path_up_inner = final_path_up.clone();
                let target_chat_up_inner = target_chat_up.clone();
                let caption_inner = caption.clone();
                let res = async {
                    let uploaded = client_up_inner.upload_file(&final_path_up_inner).await?;
                    client_up_inner.send_message(target_chat_up_inner, InputMessage::new().file(uploaded).text(caption_inner)).await
                        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))
                }.await;

                if res.is_ok() {
                    upload_result = res;
                    break;
                } else {
                    logger::warn(&format!("Downloader: Attempt {} to upload video failed: {:?}", attempt, res.unwrap_err()));
                    if attempt < 3 {
                        tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                    }
                }
            }

            let _ = cancel_tx.send(());

            match upload_result {
                Ok(_) => {
                    logger::info(&format!("Downloader: Uploaded video file: {:?}", final_path));
                    
                    // Update upload task to Completed
                    crate::ipc::update_task(
                        &upload_task_id,
                        crate::ipc::TaskType::Upload,
                        &upload_filename,
                        crate::ipc::TaskStatus::Completed,
                    );
                    let upload_task_id_rm = upload_task_id.clone();
                    tokio::spawn(async move {
                        tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                        crate::ipc::remove_task(&upload_task_id_rm);
                    });

                    // Remove meta file
                    let _ = tokio::fs::remove_file(&meta_path).await;

                    if let Err(e) = tokio::fs::remove_file(&final_path).await {
                        logger::error(&format!("Downloader: Failed to clean up downloaded file {:?}: {}", final_path, e));
                    } else {
                        logger::info(&format!("Downloader: Cleaned up temporary video file: {:?}", final_path));
                    }

                    // Delete the original message and all prompt messages from Telegram
                    let mut delete_ids = vec![msg_id];
                    delete_ids.extend(info_msg_ids);
                    logger::info(&format!("Downloader: Deleting original message and prompts (IDs: {:?}) from Telegram...", delete_ids));
                    let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                        revoke: true,
                        id: delete_ids,
                    };
                    if let Err(e) = client.invoke(&delete_req).await {
                        logger::error(&format!("Downloader: Failed to delete messages: {}", e));
                    } else {
                        logger::info("Downloader: Successfully deleted original message and prompts from Telegram.");
                    }
                }
                Err(e) => {
                    logger::error(&format!("Downloader: Failed to upload video after 3 attempts {:?}: {:?}", final_path, e));
                    
                    // Update upload task to Failed
                    crate::ipc::update_task(
                        &upload_task_id,
                        crate::ipc::TaskType::Upload,
                        &upload_filename,
                        crate::ipc::TaskStatus::Failed(e.to_string()),
                    );
                    let upload_task_id_rm = upload_task_id.clone();
                    tokio::spawn(async move {
                        tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                        crate::ipc::remove_task(&upload_task_id_rm);
                    });

                    let mut delete_ids = vec![msg_id];
                    delete_ids.extend(info_msg_ids);
                    let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                        revoke: true,
                        id: delete_ids,
                    };
                    let _ = client.invoke(&delete_req).await;
                    let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 上传视频失败 (已重试 3 次): {:?}", url, e)).await;
                }
            }
        }
        Ok(status) => {
            let err_msg = if !stderr_content.is_empty() {
                stderr_content.trim().to_string()
            } else {
                format!("Exit code: {:?}", status.code())
            };
            logger::error(&format!("Downloader: yt-dlp execution failed: {}", err_msg));

            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Failed(err_msg.clone()),
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut delete_ids = vec![msg_id];
            delete_ids.extend(info_msg_ids);
            let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                revoke: true,
                id: delete_ids,
            };
            let _ = client.invoke(&delete_req).await;
            let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ yt-dlp 下载失败: {}", url, err_msg)).await;
        }
        Err(e) => {
            let err_msg = format!("Failed to run/wait yt-dlp: {}", e);
            logger::error(&err_msg);

            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Failed(err_msg.clone()),
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut delete_ids = vec![msg_id];
            delete_ids.extend(info_msg_ids);
            let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                revoke: true,
                id: delete_ids,
            };
            let _ = client.invoke(&delete_req).await;
            let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 运行 yt-dlp 失败: {}", url, e)).await;
        }
    }
}

#[derive(Deserialize, Debug)]
struct FxMediaItem {
    #[serde(rename = "type")]
    media_type: String,
    url: String,
}

#[derive(Deserialize, Debug)]
struct FxVideo {
    url: String,
}

#[derive(Deserialize, Debug)]
struct FxMedia {
    all: Option<Vec<FxMediaItem>>,
    videos: Option<Vec<FxVideo>>,
}

#[derive(Deserialize, Debug)]
struct FxTweet {
    media: Option<FxMedia>,
    _text: Option<String>,
}

#[derive(Deserialize, Debug)]
struct FxResponse {
    code: i32,
    tweet: Option<FxTweet>,
}

fn extract_tweet_id(url: &str) -> Option<String> {
    if let Some(pos) = url.find("/status/") {
        let start = pos + "/status/".len();
        let end = url[start..].find(|c: char| !c.is_numeric()).unwrap_or(url[start..].len());
        let id = &url[start..start + end];
        if !id.is_empty() {
            return Some(id.to_string());
        }
    }
    None
}

async fn try_download_twitter_media(
    client: &Client,
    target_chat: &PeerRef,
    url: &str,
    msg_id: i32,
    download_dir: &Path,
    info_msg_ids: &mut Vec<i32>,
) -> Result<bool, String> {
    // 1. Extract tweet ID
    let tweet_id = match extract_tweet_id(url) {
        Some(id) => id,
        None => return Ok(false), // Not a status URL, fallback to yt-dlp
    };

    // 2. Fetch from fxtwitter
    let api_url = format!("https://api.fxtwitter.com/status/{}", tweet_id);
    logger::info(&format!("Downloader: Fetching tweet media from: {}", api_url));

    let output = tokio::process::Command::new("curl")
        .args(&[
            "-s",
            "-A",
            "magebot/0.1.1",
            &api_url,
        ])
        .output()
        .await
        .map_err(|e| format!("Failed to run curl: {}", e))?;

    if !output.status.success() {
        return Err("curl request to fxtwitter failed".to_string());
    }

    let response_str = String::from_utf8_lossy(&output.stdout);
    let response: FxResponse = serde_json::from_str(&response_str)
        .map_err(|e| format!("Failed to parse fxtwitter response: {}", e))?;

    if response.code != 200 {
        return Err(format!("fxtwitter API returned code {}", response.code));
    }

    let tweet = match response.tweet {
        Some(t) => t,
        None => return Err("fxtwitter response missing tweet field".to_string()),
    };

    let media = match tweet.media {
        Some(m) => m,
        None => return Ok(false), // No media, let yt-dlp check
    };

    // Check if there are any videos/gifs.
    let video_url = media.videos.as_ref()
        .and_then(|v| v.first())
        .map(|v| v.url.clone());

    if let Some(vid_url) = video_url {
        logger::info(&format!("Downloader: Found video in tweet: {}", vid_url));
        
        let dl_task_id = format!("dl_tw_vid_{}", tweet_id);
        let filename_display = format!("{}.mp4", tweet_id);
        let file_path = download_dir.join(&filename_display);

        // Register download task
        crate::ipc::update_task(
            &dl_task_id,
            crate::ipc::TaskType::Download,
            &filename_display,
            crate::ipc::TaskStatus::Downloading {
                progress: 10.0,
                speed: "Connecting...".to_string(),
                eta: "--s".to_string(),
            },
        );

        // Download using curl
        let dl_output = tokio::process::Command::new("curl")
            .args(&[
                "-s",
                "-o",
                file_path.to_str().unwrap(),
                &vid_url,
            ])
            .output()
            .await;

        match dl_output {
            Ok(out) if out.status.success() => {
                logger::info("Downloader: Video downloaded successfully from fxtwitter CDN.");
                
                // Update to uploading task
                let ul_task_id = format!("ul_tw_vid_{}", tweet_id);
                crate::ipc::remove_task(&dl_task_id);

                let file_size = tokio::fs::metadata(&file_path).await.map(|m| m.len()).unwrap_or(0);
                crate::ipc::update_task(
                    &ul_task_id,
                    crate::ipc::TaskType::Upload,
                    &filename_display,
                    crate::ipc::TaskStatus::Pending,
                );

                // Wait for a slot in the upload queue
                let semaphore = crate::watcher::get_upload_semaphore();
                let _permit = semaphore.acquire().await;

                crate::ipc::update_task(
                    &ul_task_id,
                    crate::ipc::TaskType::Upload,
                    &filename_display,
                    crate::ipc::TaskStatus::Uploading {
                        progress: 0.0,
                        speed: "2.4 MiB/s".to_string(),
                        eta: "--s".to_string(),
                    },
                );

                // Spawn background simulation for upload progress
                let ul_task_id_clone = ul_task_id.clone();
                let filename_display_clone = filename_display.clone();
                let (cancel_tx, mut cancel_rx) = tokio::sync::oneshot::channel::<()>();
                
                tokio::spawn(async move {
                    let speed_bytes = 2_500_000_u64;
                    let mut elapsed = 0.0;
                    let tick_sec = 0.5;
                    loop {
                        tokio::select! {
                            _ = tokio::time::sleep(std::time::Duration::from_millis(500)) => {
                                elapsed += tick_sec;
                                let uploaded = (elapsed * speed_bytes as f64) as u64;
                                let progress = if file_size > 0 {
                                    ((uploaded as f64 / file_size as f64) * 100.0).min(95.0)
                                } else {
                                    95.0
                                };
                                let speed_str = "2.4 MiB/s".to_string();
                                let eta_str = if file_size > uploaded {
                                    format!("{}s", ((file_size - uploaded) / speed_bytes).max(1))
                                } else {
                                    "1s".to_string()
                                };

                                crate::ipc::update_task(
                                    &ul_task_id_clone,
                                    crate::ipc::TaskType::Upload,
                                    &filename_display_clone,
                                    crate::ipc::TaskStatus::Uploading {
                                        progress,
                                        speed: speed_str,
                                        eta: eta_str,
                                    },
                                );
                            }
                            _ = &mut cancel_rx => {
                                break;
                            }
                        }
                    }
                });

                let caption = format!("[Uploaded] {}", url);
                let upload_result = client.upload_file(&file_path).await;
                let _ = cancel_tx.send(()); // Stop simulation

                match upload_result {
                    Ok(uploaded) => {
                        if let Err(e) = client.send_message(target_chat.clone(), InputMessage::new().file(uploaded).text(caption)).await {
                            logger::error(&format!("Downloader: Failed to send video message: {}", e));
                        }

                        crate::ipc::update_task(
                            &ul_task_id,
                            crate::ipc::TaskType::Upload,
                            &filename_display,
                            crate::ipc::TaskStatus::Completed,
                        );

                        // Clean up
                        let _ = tokio::fs::remove_file(&file_path).await;

                        let mut delete_ids = vec![msg_id];
                        delete_ids.extend(info_msg_ids.clone());
                        let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                            revoke: true,
                            id: delete_ids,
                        };
                        let _ = client.invoke(&delete_req).await;
                    }
                    Err(e) => {
                        logger::error(&format!("Downloader: Upload failed: {}", e));
                        crate::ipc::update_task(
                            &ul_task_id,
                            crate::ipc::TaskType::Upload,
                            &filename_display,
                            crate::ipc::TaskStatus::Failed(e.to_string()),
                        );
                    }
                }

                tokio::spawn(async move {
                    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                    crate::ipc::remove_task(&ul_task_id);
                });

                return Ok(true);
            }
            Ok(out) => {
                logger::error(&format!("Downloader: curl failed to download video: status {:?}", out.status));
                crate::ipc::update_task(
                    &dl_task_id,
                    crate::ipc::TaskType::Download,
                    &filename_display,
                    crate::ipc::TaskStatus::Failed(format!("curl status {:?}", out.status)),
                );
            }
            Err(e) => {
                logger::error(&format!("Downloader: Failed to run curl for video download: {}", e));
                crate::ipc::update_task(
                    &dl_task_id,
                    crate::ipc::TaskType::Download,
                    &filename_display,
                    crate::ipc::TaskStatus::Failed(e.to_string()),
                );
            }
        }

        tokio::spawn(async move {
            tokio::time::sleep(std::time::Duration::from_secs(5)).await;
            crate::ipc::remove_task(&dl_task_id);
        });

        // If video download via fxtwitter failed, fall back to yt-dlp!
        return Ok(false);
    }

    let all_items = match media.all {
        Some(items) => items,
        None => return Ok(false),
    };

    // Filter to get photo URLs
    let photo_urls: Vec<String> = all_items.iter()
        .filter(|item| item.media_type == "photo")
        .map(|item| item.url.clone())
        .collect();

    if photo_urls.is_empty() {
        return Ok(false); // No photos, fallback
    }

    logger::info(&format!("Downloader: Found {} photos in tweet. Starting download...", photo_urls.len()));

    // Keep track of the task ID for progress display
    let upload_task_id = format!("ul_tw_img_{}", tweet_id);
    let upload_filename = format!("tweet_images_{}", tweet_id);

    // Register task
    crate::ipc::update_task(
        &upload_task_id,
        crate::ipc::TaskType::Upload,
        &upload_filename,
        crate::ipc::TaskStatus::Uploading {
            progress: 0.0,
            speed: "N/A".to_string(),
            eta: "N/A".to_string(),
        },
    );

    let mut downloaded_files = Vec::new();

    for (idx, photo_url) in photo_urls.iter().enumerate() {
        // Download the photo using curl
        let ext = if photo_url.contains(".png") { "png" } else { "jpg" };
        let file_path = download_dir.join(format!("{}_{}.{}", tweet_id, idx, ext));
        
        logger::info(&format!("Downloader: Downloading photo {} from {}", idx + 1, photo_url));
        let dl_output = tokio::process::Command::new("curl")
            .args(&[
                "-s",
                "-o",
                file_path.to_str().unwrap(),
                photo_url,
            ])
            .output()
            .await;

        match dl_output {
            Ok(out) if out.status.success() => {
                downloaded_files.push(file_path);
            }
            Ok(out) => {
                logger::error(&format!("Downloader: Failed to download photo {}: curl status {:?}", idx + 1, out.status));
            }
            Err(e) => {
                logger::error(&format!("Downloader: Failed to run curl for photo {}: {}", idx + 1, e));
            }
        }
    }

    if downloaded_files.is_empty() {
        crate::ipc::update_task(
            &upload_task_id,
            crate::ipc::TaskType::Upload,
            &upload_filename,
            crate::ipc::TaskStatus::Failed("所有图片下载失败".to_string()),
        );
        let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 所有图片下载失败", url)).await;
        return Ok(true); // Handled (but failed)
    }

    // Now upload each file and send
    logger::info("Downloader: Uploading downloaded photos to Telegram...");

    // Register as Pending
    crate::ipc::update_task(
        &upload_task_id,
        crate::ipc::TaskType::Upload,
        &upload_filename,
        crate::ipc::TaskStatus::Pending,
    );

    // Wait for a slot in the upload queue
    let semaphore = crate::watcher::get_upload_semaphore();
    let _permit = semaphore.acquire().await;
    
    let caption = format!("[Uploaded] {}", url);
    for (idx, path) in downloaded_files.iter().enumerate() {
        // Update progress in IPC
        let progress = ((idx + 1) as f64 / downloaded_files.len() as f64) * 100.0;
        crate::ipc::update_task(
            &upload_task_id,
            crate::ipc::TaskType::Upload,
            &upload_filename,
            crate::ipc::TaskStatus::Uploading {
                progress,
                speed: "Uploading".to_string(),
                eta: format!("{} / {}", idx + 1, downloaded_files.len()),
            },
        );

        match client.upload_file(path).await {
            Ok(uploaded) => {
                let msg = if idx == 0 {
                    InputMessage::new().file(uploaded).text(&caption)
                } else {
                    InputMessage::new().file(uploaded)
                };
                if let Err(e) = client.send_message(target_chat.clone(), msg).await {
                    logger::error(&format!("Downloader: Failed to send photo {} to Telegram: {}", idx + 1, e));
                }
            }
            Err(e) => {
                logger::error(&format!("Downloader: Failed to upload photo {} to Telegram: {}", idx + 1, e));
            }
        }

        // Clean up local temp file
        let _ = tokio::fs::remove_file(path).await;
    }

    // Mark task completed
    crate::ipc::update_task(
        &upload_task_id,
        crate::ipc::TaskType::Upload,
        &upload_filename,
        crate::ipc::TaskStatus::Completed,
    );

    // Delete the original message and all prompt messages from Telegram
    let mut delete_ids = vec![msg_id];
    delete_ids.extend(info_msg_ids.clone());
    logger::info(&format!("Downloader: Deleting original message and prompts (IDs: {:?}) from Telegram...", delete_ids));
    let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
        revoke: true,
        id: delete_ids,
    };
    let _ = client.invoke(&delete_req).await;

    // Delayed cleanup of task
    tokio::spawn(async move {
        tokio::time::sleep(std::time::Duration::from_secs(3)).await;
        crate::ipc::remove_task(&upload_task_id);
    });

    Ok(true)
}
