use std::path::{Path, PathBuf};
use std::process::Stdio;
use tokio::process::Command;
use tokio::io::AsyncBufReadExt;
use grammers_client::Client;
use grammers_session::defs::PeerRef;
use grammers_client::types::InputMessage;
use std::fs::File;
use std::io::Write;

use crate::config::Config;
use crate::logger;

fn parse_yt_dlp_progress(line: &str) -> Option<(f64, String, String)> {
    if !line.contains("[download]") {
        return None;
    }
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() >= 2 {
        for i in 1..parts.len() {
            if parts[i].ends_with('%') {
                if let Ok(percent) = parts[i].trim_end_matches('%').parse::<f64>() {
                    let mut speed = "N/A".to_string();
                    let mut eta = "N/A".to_string();
                    for j in i+1..parts.len() {
                        if parts[j] == "at" && j + 1 < parts.len() {
                            speed = parts[j+1].to_string();
                        }
                        if parts[j] == "ETA" && j + 1 < parts.len() {
                            eta = parts[j+1].to_string();
                        }
                    }
                    return Some((percent, speed, eta));
                }
            }
        }
    }
    None
}

pub fn is_video_url(text: &str) -> bool {
    let text_lower = text.to_lowercase();
    text_lower.contains("youtube.com/")
        || text_lower.contains("youtu.be/")
        || text_lower.contains("twitter.com/")
        || text_lower.contains("x.com/")
        || text_lower.contains("twitch.tv/")
}

fn detect_platform(url: &str) -> Option<&'static str> {
    let lower = url.to_lowercase();
    if lower.contains("youtube.com") || lower.contains("youtu.be") {
        Some("youtube")
    } else if lower.contains("bilibili.com") || lower.contains("bili.live") {
        Some("bilibili")
    } else if lower.contains("twitter.com") || lower.contains("x.com") {
        Some("twitter")
    } else {
        None
    }
}

fn get_domain_for_platform(platform: &str) -> String {
    match platform {
        "youtube" => ".youtube.com".to_string(),
        "bilibili" => ".bilibili.com".to_string(),
        "twitter" => ".twitter.com".to_string(),
        other => format!(".{}.com", other),
    }
}

fn convert_to_netscape_if_needed(platform: &str, content: &str) -> String {
    let trimmed = content.trim();
    if trimmed.starts_with("# Netscape HTTP Cookie File") || trimmed.starts_with("# HTTP Cookie File") {
        return trimmed.to_string();
    }
    
    let domain = get_domain_for_platform(platform);
    let mut netscape = String::new();
    netscape.push_str("# Netscape HTTP Cookie File\n");
    netscape.push_str("# This file was generated by magebot\n\n");
    
    for part in trimmed.split(';') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        if let Some((name, val)) = part.split_once('=') {
            let name = name.trim();
            let val = val.trim();
            if !name.is_empty() {
                netscape.push_str(&format!("{}\tTRUE\t/\tTRUE\t2000000000\t{}\t{}\n", domain, name, val));
            }
        }
    }
    netscape
}

struct TempCookieFile {
    path: PathBuf,
}

impl TempCookieFile {
    fn create(platform: &str, content: &str) -> Result<Self, String> {
        let mut path = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
        path.push(".magebot");
        let _ = std::fs::create_dir_all(&path);
        
        let random_suffix: u32 = rand::random();
        path.push(format!("temp_cookie_{}_{}.txt", platform, random_suffix));
        
        let converted_content = convert_to_netscape_if_needed(platform, content);
        
        let mut file = File::create(&path).map_err(|e| format!("Failed to create temp cookie file: {}", e))?;
        file.write_all(converted_content.as_bytes()).map_err(|e| format!("Failed to write temp cookie file: {}", e))?;
        
        Ok(Self { path })
    }
}

impl Drop for TempCookieFile {
    fn drop(&mut self) {
        if self.path.exists() {
            let _ = std::fs::remove_file(&self.path);
        }
    }
}

fn add_filtered_args(cmd: &mut Command, args_str: &str, filter_cookies: bool) {
    if filter_cookies {
        let mut words = args_str.split_whitespace().peekable();
        while let Some(&word) = words.peek() {
            if word == "--cookies-from-browser" {
                let _ = words.next(); // consume "--cookies-from-browser"
                let _ = words.next(); // consume the browser name (if any)
            } else if word.starts_with("--cookies-from-browser=") {
                let _ = words.next(); // consume "--cookies-from-browser=browser"
            } else {
                cmd.arg(words.next().unwrap());
            }
        }
    } else {
        for arg in args_str.split_whitespace() {
            cmd.arg(arg);
        }
    }
}

async fn get_expected_filename(
    yt_dlp_path: &str,
    yt_dlp_args: Option<&str>,
    temp_cookie_path: Option<&Path>,
    no_cookies: bool,
    download_dir: &Path,
    url: &str,
) -> Result<PathBuf, String> {
    let output_template = download_dir.join("%(id)s.%(ext)s");
    let output_str = output_template.to_string_lossy();

    let mut cmd = Command::new(yt_dlp_path);
    cmd.arg("--no-playlist");
    if let Some(args_str) = yt_dlp_args {
        add_filtered_args(&mut cmd, args_str, temp_cookie_path.is_some() || no_cookies);
    }
    if let Some(cookies) = temp_cookie_path {
        cmd.arg("--cookies");
        cmd.arg(cookies);
    } else if no_cookies {
        // Disable cookie handling to avoid DPAPI errors
        cmd.arg("--no-cookies");
    }
    cmd.args([
        "-o",
        &output_str,
        "--print",
        "filename",
        url,
    ]);

    let output = cmd
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .await
        .map_err(|e| format!("Failed to execute yt-dlp to query filename: {}", e))?;

    if !output.status.success() {
        let err_msg = String::from_utf8_lossy(&output.stderr);
        return Err(format!("yt-dlp filename query failed: {}", err_msg.trim()));
    }

    let filename_str = String::from_utf8_lossy(&output.stdout);
    let path_str = filename_str.trim();
    if path_str.is_empty() {
        return Err("yt-dlp returned empty filename".to_string());
    }

    Ok(PathBuf::from(path_str))
}

pub async fn handle_video_download(client: Client, config: Config, target_chat: PeerRef, url: String, msg_id: i32) {
    let yt_dlp_path = config.get_yt_dlp_path();
    let download_dir = config.get_download_dir();

    if let Err(e) = tokio::fs::create_dir_all(&download_dir).await {
        logger::error(&format!("Downloader: Failed to create download_dir: {}", e));
        let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
            revoke: true,
            id: vec![msg_id],
        };
        let _ = client.invoke(&delete_req).await;
        let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 无法创建下载目录: {}", url, e)).await;
        return;
    }

    let mut info_msg_ids = Vec::new();
    logger::info(&format!("Downloader: Starting download for URL: {}", url));
    if let Ok(msg) = client.send_message(target_chat.clone(), "📥 识别到视频链接，正在后台下载中，请稍候...").await {
        info_msg_ids.push(msg.id());
    }

    // Detect platform and handle cookies
    let platform = detect_platform(&url);
    let mut temp_cookie = None;
    let mut use_no_cookies = false;
    if let Some(plat) = platform {
        // Attempt to load stored encrypted cookie for the platform
        if let Ok(key) = crate::crypto::get_encryption_key() {
            if let Ok(cookies_map) = crate::crypto::load_cookies_toml() {
                if let Some(encrypted_cookie) = cookies_map.get(plat) {
                    // Decrypt and write to a temporary file
                    if let Ok(decrypted) = crate::crypto::decrypt_cookie(encrypted_cookie, &key) {
                        match TempCookieFile::create(plat, &decrypted) {
                            Ok(t) => {
                                logger::info(&format!("Downloader: Using encrypted cookie for platform '{}'", plat));
                                temp_cookie = Some(t);
                            }
                            Err(e) => {
                                logger::warn(&format!("Downloader: Failed to create temp cookie file: {}", e));
                            }
                        }
                    }
                } else {
                    // No cookie stored for this platform – tell yt-dlp not to use any cookies
                    use_no_cookies = true;
                }
            }
        }
    }

    let temp_cookie_path = temp_cookie.as_ref().map(|tc| tc.path.as_path());

    // If we decided to use --no-cookies, pass a flag via a temporary empty file path placeholder
    let no_cookies_flag = use_no_cookies;

    // Get expected output path (includes cookie handling)
    let expected_path = match get_expected_filename(&yt_dlp_path, config.yt_dlp_args.as_deref(), temp_cookie_path, no_cookies_flag, &download_dir, &url).await {
        Ok(path) => path,
        Err(e) => {
            logger::error(&format!("Downloader: Failed to get expected filename: {}", e));
            download_dir.join("video.mp4")
        }
    };

    let output_template = download_dir.join("%(id)s.%(ext)s");
    let output_str = output_template.to_string_lossy();

    logger::info(&format!("Downloader: Running yt-dlp to download to: {}", expected_path.display()));

    let mut cmd = Command::new(&yt_dlp_path);
    cmd.arg("--no-playlist");
    if let Some(ref args_str) = config.yt_dlp_args {
        add_filtered_args(&mut cmd, args_str, temp_cookie_path.is_some() || no_cookies_flag);
    }
    if let Some(cookies) = temp_cookie_path {
        cmd.arg("--cookies");
        cmd.arg(cookies);
    } else if no_cookies_flag {
        // Explicitly disable cookie usage to avoid DPAPI attempts
        cmd.arg("--no-cookies");
    }
    cmd.args([
        "-o",
        &output_str,
        &url,
    ]);

    let task_id = format!("dl_{}", url);
    let filename_display = expected_path.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "video.mp4".to_string());

    // Register active download task in IPC
    crate::ipc::update_task(
        &task_id,
        crate::ipc::TaskType::Download,
        &filename_display,
        crate::ipc::TaskStatus::Downloading {
            progress: 0.0,
            speed: "0 B/s".to_string(),
            eta: "--:--".to_string(),
        },
    );

    let mut child = match cmd
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            let err_msg = format!("Failed to spawn yt-dlp: {}", e);
            logger::error(&err_msg);
            
            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Failed(err_msg.clone()),
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut delete_ids = vec![msg_id];
            delete_ids.extend(info_msg_ids);
            if !delete_ids.is_empty() {
                let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                    revoke: true,
                    id: delete_ids,
                };
                let _ = client.invoke(&delete_req).await;
            }
            let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 运行 yt-dlp 失败: {}", url, e)).await;
            return;
        }
    };

    let stdout = child.stdout.take().unwrap();
    let stderr = child.stderr.take().unwrap();

    // Spawn task to read stdout and parse progress
    let task_id_clone = task_id.clone();
    let filename_display_clone = filename_display.clone();
    tokio::spawn(async move {
        let mut reader = tokio::io::BufReader::new(stdout).lines();
        while let Ok(Some(line)) = reader.next_line().await {
            if let Some((percent, speed, eta)) = parse_yt_dlp_progress(&line) {
                crate::ipc::update_task(
                    &task_id_clone,
                    crate::ipc::TaskType::Download,
                    &filename_display_clone,
                    crate::ipc::TaskStatus::Downloading {
                        progress: percent,
                        speed,
                        eta,
                    },
                );
            }
        }
    });

    // Capture stderr
    let mut stderr_content = String::new();
    let mut stderr_reader = tokio::io::BufReader::new(stderr).lines();
    
    let wait_result = async {
        while let Ok(Some(line)) = stderr_reader.next_line().await {
            stderr_content.push_str(&line);
            stderr_content.push('\n');
        }
        child.wait().await
    }.await;

    match wait_result {
        Ok(status) if status.success() => {
            // Update download task to Completed
            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Completed,
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut final_path = expected_path.clone();
            if !final_path.exists() {
                logger::warn(&format!(
                    "Downloader: Expected file {:?} does not exist. Scanning download directory...",
                    expected_path
                ));
                if let Ok(mut entries) = tokio::fs::read_dir(&download_dir).await {
                    let mut found = false;
                    while let Ok(Some(entry)) = entries.next_entry().await {
                        let path = entry.path();
                        if path.is_file() {
                            if let Some(stem) = expected_path.file_stem().and_then(|s| s.to_str()) {
                                if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
                                    if filename.contains(stem) {
                                        final_path = path;
                                        found = true;
                                        break;
                                    }
                                }
                             }
                        }
                    }
                    if !found {
                        logger::error("Downloader: Downloaded file not found in directory.");
                        let mut delete_ids = vec![msg_id];
                        delete_ids.extend(info_msg_ids);
                        let _ = client.invoke(&grammers_tl_types::functions::messages::DeleteMessages { revoke: true, id: delete_ids }).await;
                        let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 视频下载成功，但未能在本地找到该文件。", url)).await;
                        return;
                    }
                } else {
                    logger::error("Downloader: Downloaded file not found and directory scan failed.");
                    let mut delete_ids = vec![msg_id];
                    delete_ids.extend(info_msg_ids);
                    let _ = client.invoke(&grammers_tl_types::functions::messages::DeleteMessages { revoke: true, id: delete_ids }).await;
                    let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 视频下载成功，但未能读取下载目录。", url)).await;
                    return;
                }
            }

            logger::info(&format!("Downloader: Video downloaded successfully to {:?}", final_path));
            if let Ok(msg) = client.send_message(target_chat.clone(), "📤 下载完成，正在直接上传视频...").await {
                info_msg_ids.push(msg.id());
            }

            let upload_task_id = format!("ul_{}", final_path.file_name().unwrap().to_string_lossy());
            let upload_filename = final_path.file_name().unwrap().to_string_lossy().to_string();
            let file_size = tokio::fs::metadata(&final_path).await.map(|m| m.len()).unwrap_or(0);

            // Register active upload task in IPC
            crate::ipc::update_task(
                &upload_task_id,
                crate::ipc::TaskType::Upload,
                &upload_filename,
                crate::ipc::TaskStatus::Uploading {
                    progress: 0.0,
                    speed: "2.4 MiB/s".to_string(),
                    eta: "--s".to_string(),
                },
            );

            // Spawn background simulation task
            let upload_task_id_clone = upload_task_id.clone();
            let upload_filename_clone = upload_filename.clone();
            let (cancel_tx, mut cancel_rx) = tokio::sync::oneshot::channel::<()>();
            
            tokio::spawn(async move {
                let speed_bytes = 2_500_000_u64; // ~2.4 MiB/s
                let mut elapsed = 0.0;
                let tick_sec = 0.5;
                loop {
                    tokio::select! {
                        _ = tokio::time::sleep(std::time::Duration::from_millis(500)) => {
                            elapsed += tick_sec;
                            let uploaded = (elapsed * speed_bytes as f64) as u64;
                            let progress = if file_size > 0 {
                                ((uploaded as f64 / file_size as f64) * 100.0).min(95.0)
                            } else {
                                95.0
                            };
                            let speed_str = "2.4 MiB/s".to_string();
                            let eta_str = if file_size > uploaded {
                                format!("{}s", ((file_size - uploaded) / speed_bytes).max(1))
                            } else {
                                "1s".to_string()
                            };

                            crate::ipc::update_task(
                                &upload_task_id_clone,
                                crate::ipc::TaskType::Upload,
                                &upload_filename_clone,
                                crate::ipc::TaskStatus::Uploading {
                                    progress,
                                    speed: speed_str,
                                    eta: eta_str,
                                },
                            );
                        }
                        _ = &mut cancel_rx => {
                            break;
                        }
                    }
                }
            });

            let caption = format!("[Uploaded] {}", url);
            let client_up = client.clone();
            let final_path_up = final_path.clone();
            let target_chat_up = target_chat.clone();
            let upload_result = async {
                let uploaded = client_up.upload_file(&final_path_up).await?;
                client_up.send_message(target_chat_up, InputMessage::new().file(uploaded).text(caption)).await
                    .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))
            }.await;

            let _ = cancel_tx.send(());

            match upload_result {
                Ok(_) => {
                    logger::info(&format!("Downloader: Uploaded video file: {:?}", final_path));
                    
                    // Update upload task to Completed
                    crate::ipc::update_task(
                        &upload_task_id,
                        crate::ipc::TaskType::Upload,
                        &upload_filename,
                        crate::ipc::TaskStatus::Completed,
                    );
                    let upload_task_id_rm = upload_task_id.clone();
                    tokio::spawn(async move {
                        tokio::time::sleep(std::time::Duration::from_secs(3)).await;
                        crate::ipc::remove_task(&upload_task_id_rm);
                    });

                    if let Err(e) = tokio::fs::remove_file(&final_path).await {
                        logger::error(&format!("Downloader: Failed to clean up downloaded file {:?}: {}", final_path, e));
                    } else {
                        logger::info(&format!("Downloader: Cleaned up temporary video file: {:?}", final_path));
                    }

                    // Delete the original message and all prompt messages from Telegram
                    let mut delete_ids = vec![msg_id];
                    delete_ids.extend(info_msg_ids);
                    logger::info(&format!("Downloader: Deleting original message and prompts (IDs: {:?}) from Telegram...", delete_ids));
                    let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                        revoke: true,
                        id: delete_ids,
                    };
                    if let Err(e) = client.invoke(&delete_req).await {
                        logger::error(&format!("Downloader: Failed to delete messages: {}", e));
                    } else {
                        logger::info("Downloader: Successfully deleted original message and prompts from Telegram.");
                    }
                }
                Err(e) => {
                    logger::error(&format!("Downloader: Failed to upload video {:?}: {:?}", final_path, e));
                    
                    // Update upload task to Failed
                    crate::ipc::update_task(
                        &upload_task_id,
                        crate::ipc::TaskType::Upload,
                        &upload_filename,
                        crate::ipc::TaskStatus::Failed(e.to_string()),
                    );
                    let upload_task_id_rm = upload_task_id.clone();
                    tokio::spawn(async move {
                        tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                        crate::ipc::remove_task(&upload_task_id_rm);
                    });

                    let mut delete_ids = vec![msg_id];
                    delete_ids.extend(info_msg_ids);
                    let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                        revoke: true,
                        id: delete_ids,
                    };
                    let _ = client.invoke(&delete_req).await;
                    let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 上传视频失败: {:?}", url, e)).await;
                }
            }
        }
        Ok(status) => {
            let err_msg = if !stderr_content.is_empty() {
                stderr_content.trim().to_string()
            } else {
                format!("Exit code: {:?}", status.code())
            };
            logger::error(&format!("Downloader: yt-dlp execution failed: {}", err_msg));

            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Failed(err_msg.clone()),
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut delete_ids = vec![msg_id];
            delete_ids.extend(info_msg_ids);
            let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                revoke: true,
                id: delete_ids,
            };
            let _ = client.invoke(&delete_req).await;
            let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ yt-dlp 下载失败: {}", url, err_msg)).await;
        }
        Err(e) => {
            let err_msg = format!("Failed to run/wait yt-dlp: {}", e);
            logger::error(&err_msg);

            crate::ipc::update_task(
                &task_id,
                crate::ipc::TaskType::Download,
                &filename_display,
                crate::ipc::TaskStatus::Failed(err_msg.clone()),
            );
            let task_id_rm = task_id.clone();
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                crate::ipc::remove_task(&task_id_rm);
            });

            let mut delete_ids = vec![msg_id];
            delete_ids.extend(info_msg_ids);
            let delete_req = grammers_tl_types::functions::messages::DeleteMessages {
                revoke: true,
                id: delete_ids,
            };
            let _ = client.invoke(&delete_req).await;
            let _ = client.send_message(target_chat.clone(), format!("[Failed] {}\n❌ 运行 yt-dlp 失败: {}", url, e)).await;
        }
    }
}
